from __future__ import annotations

from .models import DomainCluster, SourceFormat, SourceSpec

REFERENCE_BOOKS: tuple[SourceSpec, ...] = (
    SourceSpec(
        id="book_prize",
        title="The Prize: The Epic Quest for Oil, Money & Power",
        url="https://en.wikipedia.org/wiki/The_Prize:_The_Epic_Quest_for_Oil,_Money,_and_Power",
        publisher="Daniel Yergin",
        tier=1,
        domain=DomainCluster.GEOPOLITICS,
        format=SourceFormat.METADATA_ONLY,
        fetch="http_get",
        enabled=False,
        tags=("geopolitics", "history", "must_read"),
        notes="Acquire licensed copy; ingest via source_ingest.preprocess after OCR.",
    ),
    SourceSpec(
        id="book_oil101",
        title="Oil 101",
        url="local_knowledge_sources/oil101.txt",
        publisher="Morgan Downey",
        tier=1,
        domain=DomainCluster.TRADING_MECHANICS,
        format=SourceFormat.METADATA_ONLY,
        enabled=False,
        tags=("physical_trading", "refining", "dictionary"),
        notes="Already in repo; run source_ingest.preprocess on oil101.txt.",
    ),
    SourceSpec(
        id="book_king_of_oil",
        title="The King of Oil",
        url="https://en.wikipedia.org/wiki/Marc_Rich",
        publisher="Daniel Ammann",
        tier=2,
        domain=DomainCluster.TRADING_MECHANICS,
        format=SourceFormat.METADATA_ONLY,
        enabled=False,
        tags=("physical_trading", "arbitrage"),
        notes="Licensed book — metadata only.",
    ),
    SourceSpec(
        id="book_trading_nat_gas",
        title="Trading Natural Gas: A Non-Technical Guide",
        url="https://www.goodreads.com/book/show/10728427-trading-natural-gas",
        publisher="Fletcher Sturm",
        tier=2,
        domain=DomainCluster.INFRASTRUCTURE,
        format=SourceFormat.METADATA_ONLY,
        enabled=False,
        tags=("pipelines", "storage", "hedging"),
        notes="Licensed book — logistics parallels WTI.",
    ),
)

DOWNLOADABLE_SOURCES: tuple[SourceSpec, ...] = (
    SourceSpec(
        id="iea_omr_march_2026",
        title="IEA Oil Market Report — March 2026",
        url="https://www.iea.org/reports/oil-market-report-march-2026",
        publisher="International Energy Agency",
        tier=1,
        domain=DomainCluster.SUPPLY_DEMAND,
        format=SourceFormat.HTML,
        tags=("omr", "demand", "supply", "macro"),
    ),
    SourceSpec(
        id="iea_omr_january_2026",
        title="IEA Oil Market Report — January 2026",
        url="https://www.iea.org/reports/oil-market-report-january-2026",
        publisher="International Energy Agency",
        tier=1,
        domain=DomainCluster.SUPPLY_DEMAND,
        format=SourceFormat.HTML,
        tags=("omr", "demand", "supply", "macro"),
    ),
    SourceSpec(
        id="eia_steo",
        title="EIA Short-Term Energy Outlook",
        url="https://www.eia.gov/outlooks/steo/",
        publisher="U.S. Energy Information Administration",
        tier=1,
        domain=DomainCluster.SUPPLY_DEMAND,
        format=SourceFormat.HTML,
        tags=("steo", "forecast", "us_supply"),
    ),
    SourceSpec(
        id="eia_weekly_petroleum",
        title="EIA Weekly Petroleum Status Report",
        url="https://www.eia.gov/petroleum/supply/weekly/",
        publisher="U.S. Energy Information Administration",
        tier=1,
        domain=DomainCluster.SUPPLY_DEMAND,
        format=SourceFormat.HTML,
        tags=("wpsr", "inventories", "cushing"),
    ),
    SourceSpec(
        id="eia_crude_markets",
        title="EIA Crude Oil Markets Dashboard",
        url="https://www.eia.gov/finance/markets/crudeoil/",
        publisher="U.S. Energy Information Administration",
        tier=1,
        domain=DomainCluster.MARKET_PRICE,
        format=SourceFormat.HTML,
        tags=("wti", "prices", "fundamentals"),
    ),
    SourceSpec(
        id="eia_opendata_docs",
        title="EIA Open Data API Documentation",
        url="https://www.eia.gov/opendata/documentation.php",
        publisher="U.S. Energy Information Administration",
        tier=1,
        domain=DomainCluster.MARKET_PRICE,
        format=SourceFormat.HTML,
        tags=("api", "automation"),
    ),
    SourceSpec(
        id="opec_momr",
        title="OPEC Monthly Oil Market Report",
        url="https://www.opec.org/opec_web/en/publications/338.htm",
        publisher="OPEC",
        tier=1,
        domain=DomainCluster.SUPPLY_DEMAND,
        format=SourceFormat.HTML,
        tags=("momr", "quotas", "call_on_opec"),
    ),
    SourceSpec(
        id="cmegroup_wti_handbook_pdf",
        title="WTI and the Changing Dynamics of Global Crude Oil",
        url="https://www.cmegroup.com/education/files/wti-and-the-changing-dynamics-of-global-crude-oil.pdf",
        publisher="CME Group",
        tier=1,
        domain=DomainCluster.TRADING_MECHANICS,
        format=SourceFormat.PDF,
        tags=("wti", "nymex", "benchmark"),
    ),
    SourceSpec(
        id="cmegroup_wti_contract_specs",
        title="NYMEX WTI Contract Specifications",
        url="https://www.cmegroup.com/markets/energy/crude-oil/light-sweet-crude.contractSpecs.html",
        publisher="CME Group",
        tier=2,
        domain=DomainCluster.TRADING_MECHANICS,
        format=SourceFormat.HTML,
        enabled=False,
        notes="CME blocks automated HTML fetch; use cmegroup_wti_handbook_pdf + contract PDF from exchange.",
        tags=("contract", "delivery", "cushing"),
    ),
    SourceSpec(
        id="ine_sc_crude_handbook_pdf",
        title="INE Shanghai Crude Oil Futures Trading Handbook",
        url="https://www.ine.cn/eng/market/futures/energy/sc/manual/202004/W020250806318691873930.pdf",
        publisher="Shanghai International Energy Exchange",
        tier=1,
        domain=DomainCluster.TRADING_MECHANICS,
        format=SourceFormat.PDF,
        region="asia",
        tags=("ine", "sc_contract", "classification"),
    ),
    SourceSpec(
        id="fred_wti_spot",
        title="FRED: Crude Oil WTI Spot Price (DCOILWTICO)",
        url="https://fred.stlouisfed.org/graph/fredgraph.csv?id=DCOILWTICO",
        publisher="Federal Reserve Bank of St. Louis",
        tier=1,
        domain=DomainCluster.MARKET_PRICE,
        format=SourceFormat.JSON,
        optional=True,
        tags=("wti", "spot", "timeseries"),
        notes="Prefer eia_series_wti_spot when FRED times out from your network.",
    ),
    SourceSpec(
        id="eia_series_wti_spot",
        title="EIA API: WTI Cushing spot price series",
        url="https://api.eia.gov/v2/",
        publisher="U.S. Energy Information Administration",
        tier=1,
        domain=DomainCluster.MARKET_PRICE,
        format=SourceFormat.API,
        fetch="eia_api",
        eia_series_id="petroleum/pri/spt/data/?frequency=daily&data[0]=value&facets[product][]=EPCWTI&sort[0][column]=period&sort[0][direction]=desc&length=5000",
        tags=("wti", "cushing", "api"),
    ),
    SourceSpec(
        id="eia_series_us_crude_stocks",
        title="EIA API: U.S. crude oil stocks ex SPR",
        url="https://api.eia.gov/v2/",
        publisher="U.S. Energy Information Administration",
        tier=1,
        domain=DomainCluster.SUPPLY_DEMAND,
        format=SourceFormat.API,
        fetch="eia_api",
        eia_series_id="petroleum/stoc/wstk/data/?frequency=weekly&data[0]=value&facets[series][]=WCESTUS1&sort[0][column]=period&sort[0][direction]=desc&length=2000",
        tags=("inventories", "wpsr"),
    ),
    SourceSpec(
        id="eia_series_cushing_stocks",
        title="EIA API: Cushing OK crude stocks",
        url="https://api.eia.gov/v2/",
        publisher="U.S. Energy Information Administration",
        tier=1,
        domain=DomainCluster.SUPPLY_DEMAND,
        format=SourceFormat.API,
        fetch="eia_api",
        eia_series_id="petroleum/stoc/wstk/data/?frequency=weekly&data[0]=value&facets[series][]=WCESTUS2&sort[0][column]=period&sort[0][direction]=desc&length=2000",
        tags=("cushing", "wti_delivery"),
    ),
    SourceSpec(
        id="unctad_rmt2024",
        title="UNCTAD Review of Maritime Transport 2024",
        url="https://unctad.org/system/files/official-document/rmt2024_en.pdf",
        publisher="UNCTAD",
        tier=1,
        domain=DomainCluster.MARITIME_LOGISTICS,
        format=SourceFormat.PDF,
        tags=("vlcc", "ton_mile", "chokepoints"),
    ),
    SourceSpec(
        id="unctad_maritime_energy",
        title="UNCTAD: Maritime Transport and Energy",
        url="https://unctad.org/system/files/official-document/cimem7d32_en_0.pdf",
        publisher="UNCTAD",
        tier=2,
        domain=DomainCluster.MARITIME_LOGISTICS,
        format=SourceFormat.PDF,
        tags=("shipping", "energy"),
    ),
    SourceSpec(
        id="kpmg_geopolitics_oil_gas",
        title="KPMG: The Geopolitics of Oil and Gas",
        url="https://assets.kpmg.com/content/dam/kpmgsites/au/pdf/2023/geopolitics-of-oil-and-gas.pdf",
        publisher="KPMG",
        tier=1,
        domain=DomainCluster.GEOPOLITICS,
        format=SourceFormat.PDF,
        tags=("energy_security", "transition"),
    ),
    SourceSpec(
        id="mdpi_geopolitical_shocks_tail_risk",
        title="Geopolitical Shocks and Crude Oil Market Tail Risk",
        url="https://www.mdpi.com/2227-7099/14/3/92/pdf",
        publisher="MDPI (Economies)",
        tier=2,
        domain=DomainCluster.GEOPOLITICS,
        format=SourceFormat.PDF,
        tags=("tail_risk", "sanctions", "academic"),
    ),
    SourceSpec(
        id="eur_geopolitics_oil_2023",
        title="Geopolitics of Oil (Erasmus CTC, Nov 2023)",
        url="https://www.eur.nl/en/erasmusctc/media/2023-11-widdershoven-geopolitics-oil-ectc-november-2023",
        publisher="Erasmus University Rotterdam",
        tier=2,
        domain=DomainCluster.GEOPOLITICS,
        format=SourceFormat.HTML,
        tags=("geopolitics", "presentation"),
    ),
    SourceSpec(
        id="maritime_thesis_smailis",
        title="Global Maritime Energy Transportation (thesis)",
        url="https://dione.lib.unipi.gr/xmlui/bitstream/handle/unipi/17758/Smailis_23041.pdf?sequence=1",
        publisher="University of Piraeus",
        tier=2,
        domain=DomainCluster.MARITIME_LOGISTICS,
        format=SourceFormat.PDF,
        tags=("vlcc", "suezmax", "aframax"),
    ),
    SourceSpec(
        id="econstor_crude_maritime_fluctuations",
        title="Crude Oil Maritime Transportation: Market Fluctuations",
        url="https://www.econstor.eu/bitstream/10419/244054/1/1694118096.pdf",
        publisher="EconStor",
        tier=2,
        domain=DomainCluster.MARITIME_LOGISTICS,
        format=SourceFormat.PDF,
        tags=("bdti", "tanker"),
    ),
    SourceSpec(
        id="btc_terminal_ceyhan",
        title="BTC Terminal Ceyhan Port Information",
        url="https://marinership.net/documents/btc_terminal_ceyhan.pdf",
        publisher="MarineShip",
        tier=2,
        domain=DomainCluster.INFRASTRUCTURE,
        format=SourceFormat.PDF,
        region="turkey",
        tags=("terminal", "berth", "loading"),
    ),
    SourceSpec(
        id="port_aalborg_oil_terminal",
        title="Port of Aalborg Oil Terminal Regulations",
        url="https://portofaalborg.dk/wp-content/uploads/2023/03/port-information-and-safety-regulations_february-2022.pdf",
        publisher="Port of Aalborg",
        tier=2,
        domain=DomainCluster.INFRASTRUCTURE,
        format=SourceFormat.PDF,
        region="europe",
        tags=("terminal", "safety", "ship_to_shore"),
    ),
    SourceSpec(
        id="essd_ogim_paper",
        title="OGIM: Global Oil and Gas Infrastructure Mapping (ESSD)",
        url="https://essd.copernicus.org/articles/15/3761/2023/essd-15-3761-2023.pdf",
        publisher="Copernicus ESSD",
        tier=2,
        domain=DomainCluster.INFRASTRUCTURE,
        format=SourceFormat.PDF,
        tags=("pipelines", "refineries", "geospatial"),
    ),
    SourceSpec(
        id="ogim_catalog_landing",
        title="OGIM Community Catalog Project Page",
        url="https://gee-community-catalog.org/projects/ogim/",
        publisher="GEE Community Catalog",
        tier=2,
        domain=DomainCluster.INFRASTRUCTURE,
        format=SourceFormat.HTML,
        tags=("ogim", "geospatial"),
    ),
    SourceSpec(
        id="ocimf_mtis",
        title="OCIMF Marine Terminal Information System",
        url="https://www.ocimf.org/terminal-interfaces",
        publisher="OCIMF",
        tier=2,
        domain=DomainCluster.INFRASTRUCTURE,
        format=SourceFormat.HTML,
        tags=("terminal", "standards", "tanker"),
    ),
    SourceSpec(
        id="gdelt_project",
        title="GDELT Project (event intelligence hub)",
        url="https://www.gdeltproject.org/",
        publisher="GDELT",
        tier=2,
        domain=DomainCluster.GEOPOLITICS,
        format=SourceFormat.HTML,
        tags=("events", "sanctions", "news"),
    ),
    SourceSpec(
        id="jpmorgan_oil_research",
        title="J.P. Morgan Global Research: Oil Prices",
        url="https://www.jpmorgan.com/insights/global-research/commodities/oil-prices",
        publisher="J.P. Morgan",
        tier=2,
        domain=DomainCluster.GEOPOLITICS,
        format=SourceFormat.HTML,
        tags=("bank_research", "macro"),
    ),
    SourceSpec(
        id="cftc_cot_crude",
        title="CFTC Commitments of Traders (WTI-linked futures)",
        url="https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
        publisher="U.S. CFTC",
        tier=2,
        domain=DomainCluster.MARKET_PRICE,
        format=SourceFormat.HTML,
        tags=("cot", "positioning"),
    ),
    SourceSpec(
        id="tu_chemnitz_cep027",
        title="Oil Price Determinants (CEP027 working paper)",
        url="https://www.tu-chemnitz.de/wirtschaft/vwl1/RePEc/download/tch/wpaper/CEP027.pdf",
        publisher="TU Chemnitz",
        tier=2,
        domain=DomainCluster.MARKET_PRICE,
        format=SourceFormat.PDF,
        tags=("econometrics", "fundamentals"),
    ),
    SourceSpec(
        id="fsc_wti_ml_study",
        title="Predicting WTI Returns with ML (comparative study)",
        url="https://fsc.stevens.edu/predicting-wti-crude-oil-returns-using-machine-learning-a-comparative-study-of-ensemble-and-deep-learning-models/",
        publisher="Stevens Institute of Technology",
        tier=3,
        domain=DomainCluster.MARKET_PRICE,
        format=SourceFormat.HTML,
        tags=("ml", "academic"),
    ),
    SourceSpec(
        id="static_eia_country_overviews",
        title="EIA Country Overviews (major producers)",
        url="https://www.eia.gov/international/overview/",
        publisher="U.S. Energy Information Administration",
        tier=1,
        domain=DomainCluster.SUPPLY_DEMAND,
        format=SourceFormat.HTML,
        fetch="static_urls",
        max_discover=30,
        tags=("country_profile", "production"),
    ),
    SourceSpec(
        id="discover_unctad_maritime_pdfs",
        title="UNCTAD Maritime Transport PDF archive (discovered)",
        url="https://unctad.org/publications",
        publisher="UNCTAD",
        tier=2,
        domain=DomainCluster.MARITIME_LOGISTICS,
        format=SourceFormat.PDF,
        fetch="discover_links",
        discover_seed_url="https://unctad.org/publications?f%5B0%5D=topic%3A1171",
        discover_link_pattern=r'href="([^"]*rmt\d{4}[^"]*\.pdf)"',
        max_discover=15,
        tags=("maritime", "archive"),
    ),
)

EXCLUDED_PUBLISHERS = frozenset(
    {
        "equiti",
        "vantagemarkets",
        "startrader",
        "mexc",
        "capital.com",
        "acypartners",
        "puprime",
        "gffbrokers",
        "digitalaiq",
        "spiralscout",
    }
)


def all_sources() -> list[SourceSpec]:
    return list(REFERENCE_BOOKS) + list(DOWNLOADABLE_SOURCES)


def sources_for_download(max_tier: int = 2, include_books: bool = False) -> list[SourceSpec]:
    out: list[SourceSpec] = []
    for spec in DOWNLOADABLE_SOURCES:
        if not spec.enabled or spec.tier > max_tier:
            continue
        out.append(spec)
    if include_books:
        out.extend(s for s in REFERENCE_BOOKS if s.enabled)
    return out


def export_registry_json() -> list[dict]:
    rows = []
    for s in all_sources():
        rows.append(
            {
                "id": s.id,
                "title": s.title,
                "url": s.url,
                "publisher": s.publisher,
                "tier": s.tier,
                "domain": s.domain.value,
                "format": s.format.value,
                "fetch": s.fetch,
                "enabled": s.enabled,
                "optional": s.optional,
                "commodity": s.commodity,
                "region": s.region,
                "tags": list(s.tags),
                "notes": s.notes,
            }
        )
    return rows
